# netlify.toml

[build]
  # Comando para construir seu projeto Vite (isso gera a pasta 'dist')
  command = "npm run build" # Use "yarn build" if you prefer Yarn
  # Pasta que será publicada (onde o Vite coloca os arquivos compilados)
  publish = "dist"
  # Pasta onde estão nossas funções serverless
  functions = "netlify/functions"

# Regra de redirecionamento para a nossa API
[[redirects]]
  # Qualquer chamada para /api/...
  from = "/api/*"
  # ...será redirecionada para a nossa função serverless correspondente
  to = "/.netlify/functions/:splat"
  # Código de status 200 significa que é um redirecionamento interno, não um 301.
  status = 200
