# netlify.toml

[build]
  # Pasta que será publicada (nosso frontend)
  publish = "public"
  # Pasta onde estão nossas funções serverless
  functions = "netlify/functions"

# Regra de redirecionamento para a nossa API
[[redirects]]
  # Qualquer chamada para /api/...
  from = "/api/*"
  # ...será redirecionada para a nossa função serverless correspondente
  to = "/.netlify/functions/:splat"
  # Código de status 200 significa que é um redirecionamento interno, não um 301.
  status = 200